#!/bin/bash
set -e

cd $(dirname $0)/..

echo Running tests

# s390x doesn't support -race flag
if [ "${ARCH}" != "s390x" ]; then 
    go test -race -cover -tags=test ./...
else
    go test -cover -tags=test ./...
fi
